package com.psi.psieasymanager.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.psi.psieasymanager.data.bean.PxProductCategory;
import com.psi.psieasymanager.data.bean.PxProductInfo;
import com.psi.psieasymanager.data.bean.PxTableArea;
import com.psi.psieasymanager.data.bean.PxTableInfo;
import com.psi.psieasymanager.data.bean.User;

import com.psi.psieasymanager.db.PxProductCategoryDao;
import com.psi.psieasymanager.db.PxProductInfoDao;
import com.psi.psieasymanager.db.PxTableAreaDao;
import com.psi.psieasymanager.db.PxTableInfoDao;
import com.psi.psieasymanager.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pxProductCategoryDaoConfig;
    private final DaoConfig pxProductInfoDaoConfig;
    private final DaoConfig pxTableAreaDaoConfig;
    private final DaoConfig pxTableInfoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PxProductCategoryDao pxProductCategoryDao;
    private final PxProductInfoDao pxProductInfoDao;
    private final PxTableAreaDao pxTableAreaDao;
    private final PxTableInfoDao pxTableInfoDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pxProductCategoryDaoConfig = daoConfigMap.get(PxProductCategoryDao.class).clone();
        pxProductCategoryDaoConfig.initIdentityScope(type);

        pxProductInfoDaoConfig = daoConfigMap.get(PxProductInfoDao.class).clone();
        pxProductInfoDaoConfig.initIdentityScope(type);

        pxTableAreaDaoConfig = daoConfigMap.get(PxTableAreaDao.class).clone();
        pxTableAreaDaoConfig.initIdentityScope(type);

        pxTableInfoDaoConfig = daoConfigMap.get(PxTableInfoDao.class).clone();
        pxTableInfoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        pxProductCategoryDao = new PxProductCategoryDao(pxProductCategoryDaoConfig, this);
        pxProductInfoDao = new PxProductInfoDao(pxProductInfoDaoConfig, this);
        pxTableAreaDao = new PxTableAreaDao(pxTableAreaDaoConfig, this);
        pxTableInfoDao = new PxTableInfoDao(pxTableInfoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PxProductCategory.class, pxProductCategoryDao);
        registerDao(PxProductInfo.class, pxProductInfoDao);
        registerDao(PxTableArea.class, pxTableAreaDao);
        registerDao(PxTableInfo.class, pxTableInfoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        pxProductCategoryDaoConfig.clearIdentityScope();
        pxProductInfoDaoConfig.clearIdentityScope();
        pxTableAreaDaoConfig.clearIdentityScope();
        pxTableInfoDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PxProductCategoryDao getPxProductCategoryDao() {
        return pxProductCategoryDao;
    }

    public PxProductInfoDao getPxProductInfoDao() {
        return pxProductInfoDao;
    }

    public PxTableAreaDao getPxTableAreaDao() {
        return pxTableAreaDao;
    }

    public PxTableInfoDao getPxTableInfoDao() {
        return pxTableInfoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
