package com.psi.psieasymanager.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.psi.psieasymanager.data.bean.PxProductCategory;

import com.psi.psieasymanager.data.bean.PxProductCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PX_PRODUCT_CATEGORY".
*/
public class PxProductCategoryDao extends AbstractDao<PxProductCategory, Long> {

    public static final String TABLENAME = "PX_PRODUCT_CATEGORY";

    /**
     * Properties of entity PxProductCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property PxParentCategoryId = new Property(3, Long.class, "pxParentCategoryId", false, "PX_PARENT_CATEGORY_ID");
        public final static Property PxProductCategoryId = new Property(4, Long.class, "pxProductCategoryId", false, "PX_PRODUCT_CATEGORY_ID");
    }

    private DaoSession daoSession;

    private Query<PxProductCategory> pxProductCategory_DbChildCateListQuery;

    public PxProductCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public PxProductCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PX_PRODUCT_CATEGORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"NAME\" TEXT," + // 2: name
                "\"PX_PARENT_CATEGORY_ID\" INTEGER," + // 3: pxParentCategoryId
                "\"PX_PRODUCT_CATEGORY_ID\" INTEGER);"); // 4: pxProductCategoryId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PX_PRODUCT_CATEGORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PxProductCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Long pxParentCategoryId = entity.getPxParentCategoryId();
        if (pxParentCategoryId != null) {
            stmt.bindLong(4, pxParentCategoryId);
        }
 
        Long pxProductCategoryId = entity.getPxProductCategoryId();
        if (pxProductCategoryId != null) {
            stmt.bindLong(5, pxProductCategoryId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PxProductCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Long pxParentCategoryId = entity.getPxParentCategoryId();
        if (pxParentCategoryId != null) {
            stmt.bindLong(4, pxParentCategoryId);
        }
 
        Long pxProductCategoryId = entity.getPxProductCategoryId();
        if (pxProductCategoryId != null) {
            stmt.bindLong(5, pxProductCategoryId);
        }
    }

    @Override
    protected final void attachEntity(PxProductCategory entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PxProductCategory readEntity(Cursor cursor, int offset) {
        PxProductCategory entity = new PxProductCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // pxParentCategoryId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // pxProductCategoryId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PxProductCategory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPxParentCategoryId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setPxProductCategoryId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PxProductCategory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PxProductCategory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PxProductCategory entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbChildCateList" to-many relationship of PxProductCategory. */
    public List<PxProductCategory> _queryPxProductCategory_DbChildCateList(Long pxParentCategoryId) {
        synchronized (this) {
            if (pxProductCategory_DbChildCateListQuery == null) {
                QueryBuilder<PxProductCategory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PxParentCategoryId.eq(null));
                pxProductCategory_DbChildCateListQuery = queryBuilder.build();
            }
        }
        Query<PxProductCategory> query = pxProductCategory_DbChildCateListQuery.forCurrentThread();
        query.setParameter(0, pxParentCategoryId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPxProductCategoryDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPxProductCategoryDao().getAllColumns());
            builder.append(" FROM PX_PRODUCT_CATEGORY T");
            builder.append(" LEFT JOIN PX_PRODUCT_CATEGORY T0 ON T.\"PX_PARENT_CATEGORY_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN PX_PRODUCT_CATEGORY T1 ON T.\"PX_PRODUCT_CATEGORY_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PxProductCategory loadCurrentDeep(Cursor cursor, boolean lock) {
        PxProductCategory entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PxProductCategory dbParentCategory = loadCurrentOther(daoSession.getPxProductCategoryDao(), cursor, offset);
        entity.setDbParentCategory(dbParentCategory);
        offset += daoSession.getPxProductCategoryDao().getAllColumns().length;

        PxProductCategory dbCategory = loadCurrentOther(daoSession.getPxProductCategoryDao(), cursor, offset);
        entity.setDbCategory(dbCategory);

        return entity;    
    }

    public PxProductCategory loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PxProductCategory> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PxProductCategory> list = new ArrayList<PxProductCategory>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PxProductCategory> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PxProductCategory> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
